# Generated by Django 4.2.15 on 2024-09-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('social_icone', models.CharField(max_length=255)),
                ('social_links', models.URLField()),
                ('photo', models.ImageField(upload_to='personal_photos/')),
                ('uploaded_file', models.FileField(upload_to='uploaded_files/')),
            ],
        ),
    ]
