# Generated by Django 4.2.15 on 2024-09-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=255)),
                ('social_icone', models.CharField(max_length=255)),
                ('social_links', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='social_icone',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='social_links',
        ),
    ]
