# Generated by Django 4.2.4 on 2023-08-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibrahim', '0002_alter_projects_project_details_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='contact_phone',
            field=models.CharField(max_length=12),
        ),
    ]
