# Generated by Django 4.2.4 on 2023-08-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibrahim', '0003_alter_portfolio_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='contact_phone',
            field=models.CharField(max_length=14),
        ),
    ]
