# Generated by Django 4.2.4 on 2023-08-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibrahim', '0004_alter_portfolio_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='main_title_project',
        ),
    ]
