# Generated by Django 4.2.4 on 2023-08-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibrahim', '0005_remove_projects_main_title_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='main_project_title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='main_title_service',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='main_project_title',
            field=models.CharField(default='projects', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='main_title_service',
            field=models.CharField(default='services', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='main_title_contact',
            field=models.CharField(max_length=20),
        ),
    ]
