# Generated by Django 4.2.4 on 2023-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibrahim', '0008_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='main_logo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
