# Generated by Django 4.2.4 on 2023-08-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibrahim', '0009_portfolio_main_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='projec_img',
            new_name='project_img',
        ),
    ]
