# Generated by Django 4.2.4 on 2023-08-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibrahim', '0010_rename_projec_img_projects_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_details_link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
