# Generated by Django 4.2.4 on 2023-08-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibrahim', '0011_alter_projects_project_details_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_details_link',
            field=models.URLField(blank=True, default='localhost', null=True),
        ),
    ]
