# Generated by Django 4.2.4 on 2023-08-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibrahim', '0012_alter_projects_project_details_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_img',
            field=models.ImageField(upload_to='ProjectImg'),
        ),
    ]
